branch-defaults:
  master:
    environment: Docker-react-nonginx-env
    group_suffix: null
environment-defaults:
  Docker-react-nonginx-env:
    branch: null
    repository: null
  Docker-react3-env:
    branch: null
    repository: null
  Manual-test-env:
    branch: null
    repository: null
global:
  application_name: docker-react-nonginx
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
