version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.0

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Tests
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout
      - run:
          name: Check AWS CLI Version
          command: aws --version

workflows:
  build_and_test:
    jobs:
      - build
      - deploy
