version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Tests
      - run:
          name: Run Tests
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build
